version: '3.8'

services:
  #app service
  app:
    build: 
      dockerfile: ./docker/app/Dockerfile
      target: app_dev
    depends_on:
      - db
    working_dir: /var/www
    volumes:
      - ./:/var/www:rw
    environment:
      APP_NAME: Laravel
      APP_ENV: local
      APP_DEBUG: true
      MYSQL_PORT: 3306
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
      REDIS_HOST: redis_cache
      REDIS_PORT: 6379
      XDEBUG_MODE: ${XDEBUG_MODE:-off}
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
    # extra_hosts:
    #   - host.docker.internal:host-gateway
  
  #web service
  web:
    build:
      dockerfile: ./docker/web/Dockerfile  
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./:/var/www

  #db service
  db:
    image: mysql/mysql-server:8.0
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    container_name: mysql_server
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_RANDOM_ROOT_PASSWORD: "no"
      MYSQL_PORT: ${MYSQL_PORT}

  #phpmyadmin service
  phpmyadmin_app:
    image: phpmyadmin:5.2.2-apache
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: ${MYSQL_PORT}
      PMA_ARBITRARY: 1
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - db
    volumes:
      - dbdata:/var/lib/mysql:rw
    # extra_hosts:
    #   - host.docker.internal:host-gateway

  #mailhog service
  mailhog:
    image: mailhog/mailhog
    platform: linux/amd64
    logging:
      driver: 'none'
    ports:
      - 1025:1025 
      - 8025:8025

  #redis service
  redis_cache:
    image: redis:latest
    depends_on:
      - app
    ports:
      - "6379:6379"

volumes:
  dbdata:

  